version: '3.8'

services:
  db:
    image: postgres:15
    container_name: grimoire_db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - grimoire_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: grimoire_backend
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - grimoire_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: grimoire_frontend
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - backend
    ports:
      - "4173:4173"
    networks:
      - grimoire_network

  nginx:
    image: nginx:alpine
    container_name: grimoire_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - backend
      - frontend
    networks:
      - grimoire_network

networks:
  grimoire_network:
    driver: bridge

volumes:
  postgres_data:
  