version: "3.9"

services:
  db:
    image: postgres:16.3-alpine
    container_name: grimoire_db
    restart: always
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: grimoire_backend
    depends_on:
      - db
    env_file: .env
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    container_name: grimoire_frontend
    depends_on:
      - backend
    ports:
      - "4173:4173"

  nginx:
    image: nginx:1.26.0-alpine
    container_name: grimoire_nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend

volumes:
  pgdata: