services:
  db:
    image: postgres:16-alpine
    container_name: grimoire_db
    restart: unless-stopped
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/postgres.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s

  backend:
    build:
      context: ./backend
    container_name: grimoire_backend
    env_file: .env
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    expose:
      - 3000

  frontend:
    build:
      context: ./frontend
    container_name: grimoire_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro

volumes:
  postgres_data:
  