version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: grimoire_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - grimoire_net

  backend:
    build: ./backend
    container_name: grimoire_backend
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - grimoire_net

  frontend:
    build: ./frontend
    container_name: grimoire_frontend
    restart: always
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - grimoire_net

  nginx:
    image: nginx:stable-alpine
    container_name: grimoire_nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
    networks:
      - grimoire_net

volumes:
  pgdata:

networks:
  grimoire_net:
    driver: bridge
