version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: grim
      POSTGRES_PASSWORD: grimpass
      POSTGRES_DB: grimoire
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - grimoire

  backend:
    build: ./backend
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - grimoire

  frontend:
    build: ./frontend
    networks:
      - grimoire

  nginx:
    image: nginx:1.26.0-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./certbot/www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    networks:
      - grimoire

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/certbot --email your@email.com --agree-tos --no-eff-email -d grimoire.su

volumes:
  pgdata:

networks:
  grimoire:
    driver: bridge
