version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: grimoire_frontend
    ports:
      - "3000:3000"
    networks:
      - grimoire_network

  backend:
    build: ./backend
    container_name: grimoire_backend
    ports:
      - "3001:3001"
    networks:
      - grimoire_network

  postgres:
    image: postgres:15
    container_name: grimoire_postgres
    environment:
      POSTGRES_DB: grimoire_db
      POSTGRES_USER: grimoire_user
      POSTGRES_PASSWORD: grimoire_pass
    ports:
      - "5432:5432"
    networks:
      - grimoire_network

networks:
  grimoire_network:
    driver: bridge
