version: '3.8'
services:
  db:
    image: postgres:16
    restart: unless-stopped
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - db
    env_file: .env
    expose:
      - 3000

  frontend:
    build: ./frontend
    expose:
      - 80

  nginx:
    image: nginx:1.26.0-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/reverse-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - frontend
      - backend

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c '
      certbot certonly --webroot --webroot-path=/var/www/certbot \
        --email you@example.com --agree-tos --no-eff-email \
        -d grimoire.su && \
      nginx -s reload'"

volumes:
  pgdata:
