version: "3.8"

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    container_name: grimoire_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"

  backend:
    build:
      context: ./backend
    container_name: grimoire_backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "${BACKEND_PORT}:3000"

  frontend:
    build:
      context: ./frontend
    container_name: grimoire_frontend
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT}:4173"

  nginx:
    image: nginx:1.25-alpine
    container_name: grimoire_nginx
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"

volumes:
  postgres_data:
